const events = [
  {
    id: 1,
    name: "Concert in the Park",
    date: "2023-05-23",
    time: "18:00",
    location: "Central Park, New York",
    description: "Join us for an evening of live music in the park.",
    imageUrl: "https://source.unsplash.com/random/400x300?concert",
    attendees: 150,
  },
  {
    id: 2,
    name: "Art Exhibition",
    date: "2023-05-24",
    time: "10:00",
    location: "Modern Art Museum, San Francisco",
    description: "Explore contemporary art by local artists.",
    imageUrl: "https://source.unsplash.com/random/400x300?art",
    attendees: 75,
  },
  {
    id: 3,
    name: "Food Festival",
    date: "2023-05-25",
    time: "12:00",
    location: "Downtown, Los Angeles",
    description: "Taste a variety of dishes from around the world.",
    imageUrl: "https://source.unsplash.com/random/400x300?food",
    attendees: 200,
  },
  {
    id: 4,
    name: "Tech Conference",
    date: "2023-05-26",
    time: "09:00",
    location: "Convention Center, Seattle",
    description: "Join industry leaders for discussions on the latest in tech.",
    imageUrl: "https://source.unsplash.com/random/400x300?tech",
    attendees: 300,
  },
  {
    id: 5,
    name: "Yoga Workshop",
    date: "2023-05-27",
    time: "08:00",
    location: "Beachfront, Miami",
    description: "Start your day with a relaxing yoga session by the sea.",
    imageUrl: "https://source.unsplash.com/random/400x300?yoga",
    attendees: 50,
  },
  {
    id: 6,
    name: "Book Fair",
    date: "2023-05-28",
    time: "11:00",
    location: "City Library, Boston",
    description: "Meet authors and discover new books.",
    imageUrl: "https://source.unsplash.com/random/400x300?books",
    attendees: 120,
  },
  {
    id: 7,
    name: "Charity Run",
    date: "2023-05-29",
    time: "07:00",
    location: "Riverside Park, Chicago",
    description: "Participate in a run to raise funds for a good cause.",
    imageUrl: "https://source.unsplash.com/random/400x300?run",
    attendees: 180,
  },
  {
    id: 8,
    name: "Film Screening",
    date: "2023-05-30",
    time: "19:00",
    location: "Outdoor Cinema, Austin",
    description: "Enjoy an outdoor screening of a classic movie.",
    imageUrl: "https://source.unsplash.com/random/400x300?film",
    attendees: 90,
  },
  {
    id: 9,
    name: "Farmers Market",
    date: "2023-05-31",
    time: "09:00",
    location: "Town Square, Portland",
    description: "Shop for fresh produce and homemade goods.",
    imageUrl: "https://source.unsplash.com/random/400x300?market",
    attendees: 160,
  },
  {
    id: 10,
    name: "Theater Play",
    date: "2023-06-01",
    time: "20:00",
    location: "Grand Theater, Atlanta",
    description: "Watch a live performance of a popular play.",
    imageUrl: "https://source.unsplash.com/random/400x300?theater",
    attendees: 130,
  },
];

export default events;
